repos:
  - repo: local
    hooks:
      - id: trufflehog
        name: TruffleHog
        description: Detect secrets in your data.
        entry: bash -c 'trufflehog git file://. --since-commit HEAD --results=verified,unknown --fail'
        # For running trufflehog in docker, use the following entry instead:
        # entry: bash -c 'docker run --rm -v "$(pwd):/workdir" -i --rm trufflesecurity/trufflehog:latest git file:///workdir --since-commit HEAD --results=verified,unknown --fail'
        language: system
        stages: ["pre-commit", "pre-push"]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: pretty-format-json
        args: ["--autofix"]
  - repo: local
    hooks:
      - id: prettier
        name: Run Prettier
        entry: npx prettier --write
        language: system
        files: \.json$|\.md$|\.yaml$|\.yml$
        types: [file]
        pass_filenames: true
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
#  - repo: local
#    hooks:
#      - id: run-ut
#        name: Run Pytest Tests with Coverage
#        entry: poetry run pytest --cov=ures --cov-report=term-missing
#        language: system
#        types: [python]
#        always_run: true
#        pass_filenames: false
