name: Release
on: workflow_dispatch
permissions:
  contents: read # for checkout
jobs:
  release:
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
    uses: stone-home/Action-Stone-DevOps/.github/workflows/release.yaml@trunk
    secrets:
      onepass_token: ${{ secrets.ORG_OP_ACCOUNT_TOKEN }}
